### ISSUE TITLE
Milestone 2 To do list

### ISSUE THREAD

**Issue by danielon-5** [UBC-MDS/522-Group_30-Rockstars#16]
**Here you can find the deliverables for Milestone 2:**

- [x] Script that reads and cleans data, splits, pre-process, and transforms

- [x] Script that creates EDA and tables for reader/consumer to understand

- [x] Script with machine learning analysis and summarizes the results as figures and tables

- [x] Literate code document which presents our analysis and findings

- [x]  Iterate on Milestone 1 as required per TA feedback

More details on this Milestone 2 expectations to be found [here](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone2/milestone2.md).
