### ISSUE TITLE
Some To-do Lists

### ISSUE THREAD

**Issue by williamxu7** [UBC-MDS/522-Group_30-Rockstars#4]
**Project setup**:
- [x] File and directory set up 
- [x] Teamwork contract
- [x] Code of Conduct file
- [x] Contributing file
- [x] License file

**Project Proposal: Google doc collaboration and README.md push** 
- [x] Draft proposal
- [x] Review at meeting today and finalize

**A script that downloads and saves data**
- [x] Draft Python scripts
- [x] Review at meeting today and finalize

**EDA in a code document**
- [x] Discuss at meeting today
- [x] We have more ideas, working in progress, improvement in progress (will push a draft tonight)
- [x] Review at meeting tomorrow and finalize

**Final review**
- [x] Discuss if there is anything missing, open for improvement
- [x] Release
- [x] Submit URLs

**Comment by calsvein** [comment]
This is great!

**Comment by jordanlau123** [comment]
Thanks!

**Comment by williamxu7** [comment]
To-dos finished.
